name: Lucy Test Bot notifications

on:
  push:
  pull_request:
    types: [opened, closed]
  issues:
    types: [opened, closed, reopened]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: LucyTestBot
        uses: kkvanonymous/Lucy_Test_Bot@master
        if: always()
        with:
          chat: ${{ secrets.CHAT_ID }}
          token: ${{ secrets.BOT_TOKEN }}
