name: Lucy Test Bot notifications

on:
  push:
  pull_request:
    types: [opened, closed]
  issues:
    types: [opened, closed, reopened]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set Node.js version ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: Install packages
        run: npm install
      - name: Run build
        run: npm run build:linux
      - name: LucyTestBOT
        uses: kkvanonymous/Lucy_Test_Bot@master
        if: always()
        with:
          chat: ${{ secrets.CHAT_ID }}
          token: ${{ secrets.BOT_TOKEN }}
